# Generated by Django 3.0.8 on 2020-07-07 13:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('country_code', models.IntegerField(default=91)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('whatsapp_number', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'FeMale'), ('transgender', 'Transgender')], max_length=11)),
                ('email_id', models.EmailField(max_length=150, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Information',
            },
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('vehicle_model', models.CharField(max_length=100, verbose_name='Model')),
                ('vehicle_category', models.CharField(max_length=100, verbose_name='Category')),
                ('vehicle_number', models.CharField(max_length=250, verbose_name='Vehicle Number')),
                ('Fuel_type', models.CharField(blank=True, max_length=250, verbose_name='Fuel Type')),
                ('vehicle_color', models.CharField(max_length=250, verbose_name='Vehicle Color')),
                ('parking_lot_no', models.CharField(max_length=250, verbose_name='Parking Lot No')),
                ('parking_area', models.CharField(blank=True, max_length=250, verbose_name='Parking area')),
                ('preferred_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Preferred Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cname', to='dcwapp.CustomerInformation')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Details',
            },
        ),
        migrations.CreateModel(
            name='NoOfDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('month_end_date', models.DateField()),
                ('demo_start_date', models.DateField()),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='noofdays', to='dcwapp.VehicleDetails')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_name', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('lane_number', models.CharField(blank=True, max_length=150)),
                ('block_name', models.CharField(blank=True, max_length=40, verbose_name='Block Number/ Tower No')),
                ('House_no', models.CharField(max_length=40, verbose_name='House Number/ Unit No')),
                ('address_line1', models.CharField(max_length=250)),
                ('address_line2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('zipcode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cinfo', to='dcwapp.CustomerInformation')),
            ],
            options={
                'verbose_name_plural': 'Customer Address',
            },
        ),
    ]
