# Generated by Django 3.0.8 on 2020-07-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcwapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinformation',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Profile Picture'),
        ),
    ]
