# Generated by Django 3.0.8 on 2020-07-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcwapp', '0002_customerinformation_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinformation',
            name='customer_id',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
